### ISSUE TITLE
Excellent!

### ISSUE THREAD

**Issue by grantholle** [vicgonvt/phpstorm-settings#1]
I just sent you an email about this! I should have looked at your repos closer.

How can I use these settings? Like, where do I put the XML files

**Comment by vicgonvt** [comment]
I would recommend you fork the repo to your own github account and then you can point your Phpstorm settings to a repo. Here are some instructions

https://www.jetbrains.com/help/phpstorm/settings-tools-settings-repository.html

**Comment by grantholle** [comment]
Thanks!
